
ead:
  serviceRegistry:
    username: admin
    password: admin
  auth:
    jwtSecret: QeThWmZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E)H
    jwtExpiration: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    prefer-ip-address: true

