server:
  port: ${PORT}
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update #alteracoes em objetos serao refletidos no banco de dados
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.no-contextual-creation: true #bloqueia leitura de meta informacoes que podem gerar log de erro na inicializacao do hibernate
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent

resilience4j:
  circuitbreaker:
    instances:
      circuitBrakerInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: time_based
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstances:
        maxAttempts: 3
        waitDuration: 5s

authuser:
  refreshscope:
    name: Andre Barreto
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health








