server:
  port: 8080
spring:
  application:
    name: ead-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE/
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE/
          predicates:
            - Path=/ead-course/**
        - id: notification-service
          uri: lb://EAD-NOTIFICATION-SERVICE/
          predicates:
            - Path=/ead-notification/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${URL-EUREKA-SERVER}
  instance:
    prefer-ip-address: true