server:
  port: 8080
spring:
  application:
    name: ead-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE/
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE/
          predicates:
            - Path=/ead-course/**
        - id: notification-service
          uri: lb://EAD-NOTIFICATION-SERVICE/
          predicates:
            - Path=/ead-notification/**
ead:
  serviceRegistry:
    username: admin
    password: admin


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@${EUREKA-SERVER}:8761/eureka'
  instance:
    hostname: ead-gateway-service
    #prefer-ip-address: true