server:
  port: ${port}
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  datasource:
    url:  ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://dljpvpuf:krd992tzYuOUDUm43gevu0m3i5oueHky@toad.rmq.cloudamqp.com/dljpvpuf

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand;
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
